### ISSUE TITLE
Figure out where we're sleeping.

### ISSUE THREAD

**Issue by jklausa** [jklausa/miami-2016#1]

**Comment by jklausa** [comment]
@justmaku should come up with some proposals.

**Comment by justMaku** [comment]
You can copy it from the spreadsheet.

Wysłane z iPhone'a

Dnia 04.11.2016 o godz. 16:59 Jan Klausa notifications@github.com napisał(a):

**Comment by jklausa** [comment]
Partialy solved by #5 and #6.

**Comment by jklausa** [comment]
~~done~~
